import { type Doctor } from '../lib/data_service';

export const DOCTORS_SEED: Omit<Doctor, 'id'>[] = [
  {
    name_ku: 'دکتۆر دلێر کەریم محمد',
    name_en: 'Dr. Dler Karim Mohammed',
    specialty_ku: 'نەشتەرگەری چاو',
    specialty_en: 'Ophthalmology',
    certification_ku: 'ماستەر / دیبلۆمی باڵا لە نەشتەرگەری و نەخۆشییەکانی چاو؛ بەکالۆریۆس لە هەناوی و نەشتەرگەری گشتی',
    certification_en: 'Master / Higher Diploma in Ophthalmology; MBChB',
    clinic_ku: 'سەنتەری چاوی هەڵەبجە - نەخۆشخانەی ئامێزی تایبەت',
    clinic_en: 'Halabja Eye Center - Amez Private Hospital',
    address_ku: 'پارێزگای هەڵەبجە - شەقامی ئاسۆ حاجی محمد بامۆکی',
    address_en: 'Halabja - Aso Haji Mohammed Bamoki St.',
    workdays_ku: 'یەکشەممە، دووشەممە، سێشەممە، چوارشەممە',
    workdays_en: 'Sun, Mon, Tue, Wed',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501067369',
    phoneNumber: '07501067369 / 07740153737',
    sourceLink: 'https://www.facebook.com/reel/1219828047017524/',
    experience: 15,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆر رامیار عبداللە',
    name_en: 'Dr. Ramyar Abdullah',
    specialty_ku: 'نەشتەرگەری چاو',
    specialty_en: 'Ophthalmology',
    certification_ku: 'پسپۆری نەشتەرگەری چاو / پسپۆری وردی گلێنە و ئاوی سپی و لێزیک / فیمتۆ لەوڵاتی ئەمریکا',
    certification_en: 'Ophthalmology Specialist / Cornea, Cataract & LASIK Specialist (USA)',
    clinic_ku: 'سەنتەری چاوی هەڵەبجە - نەخۆشخانەی ئامێزی تایبەت',
    clinic_en: 'Halabja Eye Center - Amez Private Hospital',
    address_ku: 'پارێزگای هەڵەبجە - شەقامی ئاسۆ حاجی محمد بامۆکی',
    address_en: 'Halabja - Aso Haji Mohammed Bamoki St.',
    workdays_ku: 'پێنجشەممە (سەردانی پەرتووکەکراو)',
    workdays_en: 'Thursday (By Appointment)',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501067369',
    phoneNumber: '07501067369 / 07740153737',
    sourceLink: 'https://www.facebook.com/reel/1258484943123815/',
    experience: 12,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆر گۆران محمد',
    name_en: 'Dr. Goran Mohammed',
    specialty_ku: 'پێست',
    specialty_en: 'Dermatology',
    certification_ku: '',
    certification_en: 'Dermatologist',
    clinic_ku: 'سەنتەری پێست و جوانکاری د.گۆران محمد - نەخۆشخانەی ئامێزی تایبەت',
    clinic_en: 'Dr. Goran Dermatology Center - Amez Private Hospital',
    address_ku: 'پارێزگای هەڵەبجە - شەقامی ئاسۆ حاجی محمد بامۆکی - نەخۆشخانەی ئامێزی تایبەت',
    address_en: 'Halabja - Aso Haji Mohammed Bamoki St. - Amez Hospital',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501309891',
    phoneNumber: '07501309891 / 07734013301',
    sourceLink: 'https://www.facebook.com/reel/26639147729025013/',
    experience: 10,
    availableToday: true,
    bio_ku: 'داشکاندنی ٣٠٪ لە مانگی ڕەمەزان',
    bio_en: '30% Discount in Ramadan',
    fee: ''
  },
  {
    name_ku: 'دکتۆرە ڤیان هیوا هەورامی',
    name_en: 'Dr. Vian Hiwa Hawrani',
    specialty_ku: 'نەشتەرگەری گشتی',
    specialty_en: 'General Surgery',
    certification_ku: 'بۆرد (دکتۆرا) لە نەشتەرگەری و جوانکاری و ڕێکاری؛ ڕاهێنانی نەشتەرگەری مایکرۆسکۆپ (هندستان)',
    certification_en: 'Board Certified General & Plastic Surgeon; Micro-surgery Training (India)',
    clinic_ku: 'سەنتەری پێست و جوانکاری - نەخۆشخانەی ئامێزی تایبەت',
    clinic_en: 'Dermatology & Cosmetology Center - Amez Private Hospital',
    address_ku: 'پارێزگای هەڵەبجە - شەقامی ئاسۆ حاجی محمد بامۆکی',
    address_en: 'Halabja - Aso Haji Mohammed Bamoki St.',
    workdays_ku: 'سێشەممە، چوارشەممە',
    workdays_en: 'Tue, Wed',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501309891',
    phoneNumber: '07501309891 / 07734013301',
    sourceLink: 'https://www.facebook.com/reel/1287481683205653/',
    experience: 14,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆر بەسۆز یونس عزیز',
    name_en: 'Dr. Basoz Younis Aziz',
    specialty_ku: 'دەم و ددان',
    specialty_en: 'Dentistry',
    certification_ku: '',
    certification_en: 'Dentist',
    clinic_ku: 'Amez Dental Health - نەخۆشخانەی ئامێزی تایبەت',
    clinic_en: 'Amez Dental Health - Amez Private Hospital',
    address_ku: 'پارێزگای هەڵەبجە - شەقامی ئاسۆ حاجی محمد بامۆکی - نهۆمی سێیەم',
    address_en: 'Halabja - Aso Haji Mohammed Bamoki St. - 3rd Floor',
    workdays_ku: 'شەممە تا پێنجشەممە',
    workdays_en: 'Sat - Thu',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07511861828',
    phoneNumber: '07511861828 / 07706484646',
    sourceLink: 'https://www.facebook.com/reel/4642364402664217/',
    experience: 8,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆرە هدی أحمد رشید',
    name_en: 'Dr. Huda Ahmed Rashid',
    specialty_ku: 'ژنان و مناڵبوون',
    specialty_en: 'Gynecology',
    certification_ku: 'دکتۆرای عەرەبی لە نەشتەرگەری و نەخۆشییەکانی ژنان و منداڵبوون',
    certification_en: 'Arab Board in Gynecology & Obstetrics',
    clinic_ku: 'تەلاری پزیشکی ئایندە',
    clinic_en: 'Future Medical Center',
    address_ku: 'هەڵەبجەی شەهید - تەلاری پزیشکی ئایندە - بەرامبەر دەرمانخانەی شیفا',
    address_en: 'Halabja - Future Medical Center - Opp. Shifa Pharmacy',
    workdays_ku: 'شەممە، یەک شەممە، سێشەممە، چوارشەممە',
    workdays_en: 'Sat, Sun, Tue, Wed',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501545000',
    phoneNumber: '7501545000',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid0woYdtZLK338HNAtD2GrvkytNpgJ1zM9uHfDNvqc5mxYKdoGAzodBLNj6uwfYutx5l&id=100070677467086',
    experience: 15,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆر ڕێبوار فەرەج باوەیسی',
    name_en: 'Dr. Rebwar Faraj Baweisi',
    specialty_ku: 'هەناوی',
    specialty_en: 'Internal Medicine',
    certification_ku: 'دکتۆرا (بۆرد)ی عەرەبی لە نەخۆشییەکانی هەناوی و دڵ و شەکرە و غودە؛ ئەندامی کۆمەڵەی پزیشکانی وڵاتانی عەرەبی',
    certification_en: 'Arab Board in Internal Medicine & Cardiology Specialist; Member of Arab Physician Society',
    clinic_ku: 'تەلاری پزیشکی ئایندە',
    clinic_en: 'Future Medical Center',
    address_ku: 'هەڵەبجەی شەهید - تەلاری پزیشکی ئایندە - بەرامبەر دەرمانخانەی شیفا',
    address_en: 'Halabja - Future Medical Center - Opp. Shifa Pharmacy',
    workdays_ku: 'شەممە، یەک شەممە، دوو شەممە، سێشەممە، چوار شەممە',
    workdays_en: 'Sat, Sun, Mon, Tue, Wed',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501878535',
    phoneNumber: '07501878535 / 07708994040',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid0Tvaeed65kkny4sp9TK2Hv4hPzfkg4SGFbe4dT8MfxLGpnzLcpZMUU22SaTq9fdW1l&id=100070677467086',
    experience: 18,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆر باوان محمد امین بارام کۆکۆیی',
    name_en: 'Dr. Bawan Mohammed Amin',
    specialty_ku: 'ئێسک و شکاوی',
    specialty_en: 'Orthopedics',
    certification_ku: 'دکتۆرا (بۆردی عەرەبی) لە نەشتەرگەری ئێسک و شکاوی و گۆڕینی جومگە و فەقەرات؛ شارەزا لە گۆڕینی جومگەی حەوز و ئەژنۆ و دووبارە گۆڕینی جومگە و دەرچوونی جومگەی حەوزی زگماکی',
    certification_en: 'Arab Board in Orthopedics & Spinal Surgery; Joint Replacement Specialist',
    clinic_ku: 'تەلاری پزیشکی ئایندە',
    clinic_en: 'Future Medical Center',
    address_ku: 'هەڵەبجەی شەهید - تەلاری پزیشکی ئایندە - بەرامبەر دەرمانخانەی شیفا',
    address_en: 'Halabja - Future Medical Center - Opp. Shifa Pharmacy',
    workdays_ku: 'شەممە، دوو شەممە، سێ شەممە، پێنج شەممە',
    workdays_en: 'Sat, Mon, Tue, Thu',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07728248181',
    phoneNumber: '07728248181 / 07510222181',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid02QkTBCwLzw2jRjzXTW8kJFPnHpMfXG3WF6siNE5fQC11KeyZQxdcrhp3g6gqAyc9Vl&id=100070677467086',
    experience: 12,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆرە باخان عمر کریم',
    name_en: 'Dr. Bakhan Omar Karim',
    specialty_ku: 'قوڕگ و لوت و گوێ',
    specialty_en: 'ENT',
    certification_ku: '',
    certification_en: 'ENT Specialist',
    clinic_ku: 'تەلاری پزیشکی ئایندە',
    clinic_en: 'Future Medical Center',
    address_ku: 'هەڵەبجەی شەهید - تەلاری پزیشکی ئایندە - بەرامبەر دەرمانخانەی شیفا',
    address_en: 'Halabja - Future Medical Center - Opp. Shifa Pharmacy',
    workdays_ku: 'شەممە، یەک شەممە، سێشەممە',
    workdays_en: 'Sat, Sun, Tue',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07703321001',
    phoneNumber: '07703321001 / 07501696770',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid033w2L1nTTc4dKs8gto9fyTe1Ky62rrztHY9H96ZQRRjwjJdfMmfbEwcDekV6oz61il&id=100070677467086',
    experience: 10,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'دکتۆر عیرفان احمد رشید',
    name_en: 'Dr. Irfan Ahmed Rashid',
    specialty_ku: 'تیشک و سۆنار',
    specialty_en: 'Radiology',
    certification_ku: '',
    certification_en: 'Radiology Specialist',
    clinic_ku: 'تەلاری پزیشکی ئایندە',
    clinic_en: 'Future Medical Center',
    address_ku: 'هەڵەبجەی شەهید - تەلاری پزیشکی ئایندە - بەرامبەر دەرمانخانەی شیفا',
    address_en: 'Halabja - Future Medical Center - Opp. Shifa Pharmacy',
    workdays_ku: 'شەممە، یەک شەممە، دوو شەممە، سێشەممە، چوارشەممە',
    workdays_en: 'Sat, Sun, Mon, Tue, Wed',
    location_ku: 'هەڵەبجە',
    location_en: 'Halabja',
    contact: '07501984069',
    phoneNumber: '7501984069',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid033w2L1nTTc4dKs8gto9fyTe1Ky62rrztHY9H96ZQRRjwjJdfMmfbEwcDekV6oz61il&id=100070677467086',
    experience: 15,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'د. فەرەیدوون عەدنان بەرزنجی',
    name_en: 'Dr. Faraidun Adnan Barzanji',
    specialty_ku: 'ئێسک و شکاوی',
    specialty_en: 'Orthopedics',
    certification_ku: 'دکتۆرا (بۆرد)ی عیراقی لە نەشتەرگەری و نەخۆشیەکانی ئێسک و شکاوی - بەکالۆریۆس لە هەناوی و نەشتەرگەری گشتی - M.B.CH.B - FIBMS(Ortho)',
    certification_en: 'Iraq Board in Orthopedics Specialist; MBChB; FIBMS',
    clinic_ku: 'کلینیکی پزیشکی ئاشتی',
    clinic_en: 'Ashti Medical Clinic',
    address_ku: 'شەقامی پزیشکان - بەرامبەر بازاڕی لەنگە',
    address_en: 'Physicians St. - Opp. Langa Market',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'ڕانیە',
    location_en: 'Rania',
    contact: '07501403816',
    phoneNumber: '07501403816 - 07701403816',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid03Gof1waNR9G6Dv5GV1orZWxwFmBs7nJYafjuU3NLnsCEbT2t8AKUMF8fmhejWfvSl&id=100083293903435',
    experience: 15,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'د. علی همزە حسین',
    name_en: 'Dr. Ali Hamza Hussain',
    specialty_ku: 'مناڵان و تازە لەدایکبووان',
    specialty_en: 'Pediatrics',
    certification_ku: 'دیبلۆمی باڵا (ماجستیر) لە نەخۆشیەکانی منداڵان و تازە لەدایک بووان - بەکالۆریۆس لە هەناوی و نەشتەرگەری گشتی - M.B.Ch.B - H.D(pediatrics)',
    certification_en: 'Higher Diploma in Pediatrics; MBChB',
    clinic_ku: 'کلینیکی پزیشکی ئاشتی',
    clinic_en: 'Ashti Medical Clinic',
    address_ku: 'شەقامی پزیشکان - بەرامبەر بازاڕی لەنگە',
    address_en: 'Physicians St. - Opp. Langa Market',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'ڕانیە',
    location_en: 'Rania',
    contact: '07707798302',
    phoneNumber: '07707798302 - 07501437309',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid0Y2mgbHeFQa1GgcMi91yA8zidCaWBwwh6qZxwnmMEBYKnTcgQkgy5YrZtemWFpkfsl&id=100083293903435',
    experience: 10,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'د. زانا مەعروف شێخانی',
    name_en: 'Dr. Zana Maruf Shikhani',
    specialty_ku: 'میزەڕۆ و گورچیلە',
    specialty_en: 'Urology',
    certification_ku: 'دکتۆرا (بۆرد) لە نەشتەرگەری گورچیلە و میزەڕۆ - بغداد - ئەندامی کۆمەڵەی کوردستانی و عێراقی و ئەوروپی بۆ نەشتەرگەری گورچیلە - بەکالۆریۆس لە هەناوی و نەشتەرگەری گشتی - M.B.ch.B - C.A.B.M.S (Urology)',
    certification_en: 'Board Certified Urologist (Baghdad); Member of European Urological Association; MBChB',
    clinic_ku: 'کلینیکی پزیشکی ئاشتی',
    clinic_en: 'Ashti Medical Clinic',
    address_ku: 'شەقامی پزیشکان - بەرامبەر بازاڕی لەنگە',
    address_en: 'Physicians St. - Opp. Langa Market',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'ڕانیە',
    location_en: 'Rania',
    contact: '07509301301',
    phoneNumber: '07509301301 (سکرتێر) - 07701900252 (دکتۆر)',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=704368299128589&id=100083293903435&substory_index=704368299128589',
    experience: 18,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'د. بەهزاد وسو حمد بەگ',
    name_en: 'Dr. Behzad Wsu Hamad Beg',
    specialty_ku: 'نەشتەرگەری گشتی',
    specialty_en: 'General Surgery',
    certification_ku: 'دکتۆرا (بۆرد) لە نەشتەرگەری کۆئەندامی هەرس و میزەڕۆ و غوددەکان - ئەندامی کۆلێژی شاهانەی بەریتانیا بۆ نەشتەرگەران - هاوەڵی کۆلێژی ئەمریکی بۆ نەشتەرگەران',
    certification_en: 'Board Certified GI Surgeon; Member of Royal College of Surgeons (UK); FACS (USA)',
    clinic_ku: 'کۆمەڵگەی پزیشکی هەنوو',
    clinic_en: 'Hanoo Medical Complex',
    address_ku: 'شەقامی گشتی - تەنیشت مزگەوتی ناجیەخان',
    address_en: 'Main St. - Beside Najia Khan Mosque',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'ڕانیە',
    location_en: 'Rania',
    contact: '07711431414',
    phoneNumber: '07711431414 - 07508881243',
    sourceLink: 'https://www.facebook.com/DhRmanzany/posts/pfbid0xoKYZwnbLn12vD6Y9Lny9m2yFQDpSXUKUe7iMSAJByXqQpG1BtM1T8rKna1bM4Hdl',
    experience: 22,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'د. باهۆز عزیز طە (بەرزنجی)',
    name_en: 'Dr. Bahoz Aziz Taha',
    specialty_ku: 'دڵ و قەستەرە',
    specialty_en: 'Cardiology',
    certification_ku: 'دکتۆرا (بۆردی عەرەبی) لە نەخۆشییە هەناوییەکان و دڵ - CABHS (Internal Medicine) 2024 - بەکالۆریۆس لە هەناوی و نەشتەرگەری گشتی - MBChB 2015',
    certification_en: 'Arab Board in Internal Medicine & Cardiology; MBChB 2015; Top rank in Iraq Board 2024',
    clinic_ku: 'کلینیکی پزیشکی نۆڤین',
    clinic_en: 'Novin Medical Clinic',
    address_ku: 'شەقامی سەرا - بەرامبەر قوتابخانەی ماکۆک',
    address_en: 'Sara St. - Opp. Makook School',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'ڕانیە',
    location_en: 'Rania',
    contact: '07512721818',
    phoneNumber: '07512721818 - 07702721818',
    sourceLink: 'https://www.facebook.com/NovinMedicalClinic/posts/pfbid031WajmoLzbnt9rHwZEtDNtJ3uRsmoyzhL2g1ahf5ghnYmz96bcHm2QCwvJWPvGBg1l',
    experience: 10,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  },
  {
    name_ku: 'د. ئاری ئەنوەر صالح',
    name_en: 'Dr. Ari Anwar Salih',
    specialty_ku: 'نەشتەرگەری مێشک و دەمار',
    specialty_en: 'Neurosurgery',
    certification_ku: 'دکتۆرا (بۆرد) لە نەشتەرگەری مێشک و دەمار و بڕبڕەی پشت و فقرات - ئەندامی دامەزراوەی ئەوروپی بۆ کۆمەڵەکانی نەشتەرگەری مێشک و دەمار (E.A.N.S)',
    certification_en: 'Board Certified Neurosurgeon & Spinal Surgeon; Member of E.A.N.S',
    clinic_ku: 'تەلاری پزیشکی میللەت',
    clinic_en: 'Millat Medical Center',
    address_ku: 'بەرامبەر مزگەوتی ناجیەخان',
    address_en: 'Opp. Najia Khan Mosque',
    workdays_ku: 'هەموو ڕۆژ',
    workdays_en: 'Daily',
    location_ku: 'ڕانیە',
    location_en: 'Rania',
    contact: '07722264303',
    phoneNumber: '07722264303 - 07509684303',
    sourceLink: 'https://www.facebook.com/permalink.php?story_fbid=pfbid0aTsTB8m4rmYBRx6KVTyCskSfvVAX2LpEC32sjHcdfg8TRqMegs3xhnEvrHPJs7Nhl&id=100064369614831',
    experience: 15,
    availableToday: true,
    bio_ku: '',
    bio_en: '',
    fee: ''
  }
];
